### ISSUE TITLE
Upgrade horizontal pod autoscaler version to autoscaling/v2

### ISSUE THREAD

**Issue by tjololo** [Altinn/altinn-studio-charts#11]
### Description

Currently we are using autoscaling/v2beta2 HorizontalPodAutoscaler to manage autoscaling of applications.

Version v2beta2 is deprecated in favour of v2 from kubernetes 1.23+ and removed in 1.26+

When all apps clusters are upgraded to 1.23+ we should upgrade to autoscaling/v2 to be prepared for the upgrade to 1.26+ (guessing it will be GA in april 2023)

### Additional Information

* [kubernetes deprecation/removal](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126)
* [Aks release calendar](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar)

### Tasks

- [x] Upgrade HorizontalPodAutoscaler to version autoscaling/v2
- [ ] Release new version of deploy chart
- [ ] Set new version as default in template

### Acceptance Criterias

- [ ] New versions of apps are deployed using HorizontalPodAutoscaler version autoscaling/v2
- [ ] Possible to upgrade existing apps to new version charts using autoscaling/v2
