### ISSUE TITLE
deployment: Update traefik.containo.us/v1alpha1 to traefik.io/v1alpha1 in chart deployment

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-studio-charts#25]
### Description

Traefik 3.0 will only support `traefik.io/v1`
Traefik migration plan is to move to `traefik.io/v1alpha1` in version >2.10.0.
Traefik 3.0 will have webhooks to translate `traefik.io/v1alpha1` to `traefik.io/v1`

### Additional Information

This is a breaking change that require version >2.10.0 in cluster.

### Tasks

- [x] Upgrade traefik to 2.10.0
- [ ] Replace `traefik.containo.us/v1alpha1` with `traefik.io/v1alpha1` in ingressroute.yaml and middleware.yaml
- [ ] Create new release

### Acceptance Criterias

- [ ] All routing work as before with new api version
